plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.4.13')
    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation platform('org.springframework.boot:spring-boot-dependencies:3.4.13')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
